// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Agent 事件载荷（跨边界契约：10 字段——可选 cliId + 可选 usageSourcePath + 可选 usedPercentage，camelCase 序列化）
 *
 * PartialEq 供 serde 往返精确断言测试使用（HUK-09）。
 * cliId 为可选（serde default）：旧信号文件（无 cliId 键）反序列化兼容，
 * 缺省由前端按 claude 兜底（MC-205 三级解析）。
 * usageSourcePath 为可选（serde default，不加 serde alias）：信号文件瞬态（亚秒~3s 存活），
 * 旧键（transcriptPath）信号降级 None——仅丢该事件用量拉取（决策 1）。
 * usedPercentage 为可选（serde default）：ContextUsage 信号携带官方 context 用量百分比
 * （claude statusline `context_window.used_percentage` 桥接），旧信号缺键降级 None。
 */
export type AgentEventPayload = { 
/**
 * 页签路由标识（环境变量 SLTERM_PANEL_ID）
 */
panelId: string, 
/**
 * 事件名（C9 10 事件之一）
 */
event: string, 
/**
 * 时间戳（毫秒）
 */
timestamp: number, 
/**
 * 会话标识
 */
sessionId: string, 
/**
 * 用量来源文件路径（可选，serde default）：旧信号缺键降级 None，仅丢该事件用量拉取；
 * 路径语义由具体 CLI 解释（claude = transcript JSONL）
 */
usageSourcePath?: string | null, 
/**
 * 当前工作目录
 */
cwd: string, 
/**
 * 工具名（仅工具事件，可缺省）
 */
toolName: string | null, 
/**
 * 通知类型（仅 Notification 事件，可缺省）
 */
notificationType: string | null, 
/**
 * CLI 标识（可选，serde default；旧信号缺省 → 前端按 claude 兼容）
 */
cliId?: string, 
/**
 * context 用量百分比（可选，serde default）：ContextUsage 信号字段——
 * 官方口径 used_percentage（0–100 float），前端经 profile 策略取整钳位
 */
usedPercentage?: number | null, };

/**
 * Agent 注入状态 DTO（C6 契约；决策 3 更名 AgentHookInjectionStatus）
 *
 * PartialEq 供 serde 往返精确断言测试使用（HUK-09）。
 * CP-024:ts-rs 生成 `src/types/agent.ts`。
 */
export type AgentHookInjectionStatus = { 
/**
 * 注入状态
 */
status: AgentInjectionStatus, 
/**
 * 已注入脚本版本号（未注入时为 null）
 */
version: number | null, 
/**
 * 待确认的可疑 statusline 原命令原文（仅 pendingConfirmation 时存在；
 * skip_serializing_if 保证其余状态序列化键集合不变——HUK-09 契约兼容）
 */
suspiciousCommand?: string, };

/**
 * 注入状态枚举（C6 契约；决策 3 更名 AgentInjectionStatus；CP-043 增待确认态）
 *
 * CP-024:ts-rs 生成 `src/types/agent.ts`。
 */
export type AgentInjectionStatus = "injected" | "notInjected" | "outdated" | "pendingConfirmation";
