// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Agent 全局目录 DTO（agent_dirs_list 返回项）
 *
 * CP-024: ts-rs 生成 `src/types/agentDirs.ts`。
 */
export type AgentGlobalDir = { 
/**
 * CLI profile id（与前端 cliProfileRegistry 键对应）
 */
cliId: string, 
/**
 * 解析后的绝对路径（home + 相对目录；未 canonicalize——前端仅作展示与命令参数回传，
 * 沙箱校验侧在 state.rs 内双侧 canonicalize 比较，symlink 场景兼容）
 */
path: string, 
/**
 * 目录当前是否存在（false → 前端展示「目录不存在」占位，不启动监听）
 */
exists: boolean, };
