// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 历史会话元数据 DTO（IPC 契约八字段，serde camelCase，硬约束 #4）
 *
 * `title_source` 为开放字符串（MC-302）：claude 值集
 * `customTitle`/`aiTitle`/`summary`/`firstPrompt`/`none`，UI 不消费具体值。
 * `cli_id` 由 provider 打标（claude provider 产出 `"claude"`）。
 */
export type AgentHistorySession = { 
/**
 * 会话 ID（claude：文件名主干 = UUID）
 */
sessionId: string, 
/**
 * 会话启动时工作目录（从 JSONL 内容解析，不反解码目录名）
 */
cwd: string | null, 
/**
 * 标题（回退链合成结果；全无时为 None）
 */
title: string | null, 
/**
 * 标题来源开放字符串（claude 值集：customTitle/aiTitle/summary/firstPrompt/none）
 */
titleSource: string, 
/**
 * 首条可见 user prompt（≤200 字符）
 */
firstPrompt: string | null, 
/**
 * 文件修改时间（毫秒时间戳）
 */
mtimeMs: number, 
/**
 * cwd 目录当前是否存在（cwd 为 null 时恒 false）
 */
cwdExists: boolean, 
/**
 * CLI 标识（provider 打标，聚合后前端按 cliId 区分来源）
 */
cliId: string, };

/**
 * 单会话标题 DTO（IPC 契约两键，serde camelCase，硬约束 #4）
 *
 * 供运行中会话页签/导航树行取与历史 session 同源的标题
 * （`agent_history_read_title`——人工验证问题 3）。`title` 为 None 表示回退链
 * 四路全无（文件缺失/无任何标题数据）——前端兜底 CLI 名（claude 等）。
 */
export type AgentHistoryTitle = { 
/**
 * 标题（回退链合成结果；全无时为 None）
 */
title: string | null, 
/**
 * 标题来源开放字符串（claude 值集：customTitle/aiTitle/summary/firstPrompt/none）
 */
titleSource: string, };
