// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type BackgroundTaskInfo = { taskId: string, title: string, enabled: boolean, intervalSec: number, intervalMin: number, intervalMax: number, };
