// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 目录条目
 *
 * CP-024:ts-rs 生成 `src/types/fs.ts`。
 */
export type DirEntry = { 
/**
 * 文件/目录名
 */
name: string, 
/**
 * 完整路径
 */
path: string, 
/**
 * 是否为目录
 */
isDir: boolean, 
/**
 * 文件大小（字节），仅文件时有值
 */
size: number | null, 
/**
 * 最后修改时间（Unix 毫秒），仅文件时有值
 */
modified: number | null, };

/**
 * 目录分页读取结果（CP-006：游标契约）
 */
export type FsReadDirPage = { 
/**
 * 本页条目（排序与过滤语义同旧整表契约）
 */
entries: Array<DirEntry>, 
/**
 * 下一页游标；None = 无更多（末页）
 */
nextCursor: string | null, };
