// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 目录条目
 *
 * CP-024:ts-rs 生成 `src/types/fs.ts`。
 */
export type DirEntry = { 
/**
 * 文件/目录名
 */
name: string, 
/**
 * 完整路径
 */
path: string, 
/**
 * 是否为目录
 */
isDir: boolean, 
/**
 * 文件大小（字节），仅文件时有值
 */
size: number | null, 
/**
 * 最后修改时间（Unix 毫秒），仅文件时有值
 */
modified: number | null, };
