// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * diff hunk 信息（old = HEAD, new = 工作区）
 *
 * CP-024:ts-rs 生成 `src/types/git.ts`。
 */
export type DiffHunk = { 
/**
 * HEAD 侧起始行号（1-based）
 */
oldStart: number, 
/**
 * HEAD 侧行数
 */
oldLines: number, 
/**
 * 工作区侧起始行号（1-based）
 */
newStart: number, 
/**
 * 工作区侧行数
 */
newLines: number, };

/**
 * 文件 git 状态条目
 *
 * CP-024:ts-rs 生成 `src/types/git.ts`。
 */
export type GitStatusEntry = { 
/**
 * 文件绝对路径（与 fs_read_dir 的 DirEntry.path 格式一致）= 当前工作区路径。
 * 语义对齐 git status：modified/added/untracked/conflict 为当前路径，
 * deleted 为被删路径（git status 显示语义），renamed 为**新路径**
 * （旧路径见 old_path——git2-rs 的 entry.path() 对 renamed 返回旧路径，
 * 命令层必须改取 delta.new_file().path()）
 */
path: string, 
/**
 * git 状态：modified | added | deleted | renamed | untracked | conflict
 */
status: string, 
/**
 * 重命名前的旧绝对路径（仅 renamed 条目有值，camelCase 序列化为 oldPath）
 */
oldPath: string | null, };
