// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 单个 hook handler（SEC-05 校验点：type 白名单 + command 非空审查）
 *
 * CP-024 扩至 C13-3 全字段矩阵（原只承载校验所需 type+command 两字段，前端
 * 手写面 HookHandlerJson 宽于 Rust 面——单源化前置扩 DTO）。校验语义不变：
 * type/command 缺失容忍为默认值，语义审查（type 白名单 / command 非空）
 * 由 S17 SEC-05 校验层执行；其余字段仅形态承载（反序列化 round-trip 保留，
 * 不再丢未知键）。
 * CP-024：ts-rs 导出命名对齐前端消费名 `HookHandlerJson`。
 */
export type HookHandlerJson = { 
/**
 * handler 类型（官方值集 command/http/mcp_tool/prompt/agent）
 */
type: string, 
/**
 * 命令串（type=command 时必填，非空审查归 SEC-05）
 */
command?: string, 
/**
 * 命令参数数组（command 型）
 */
args?: Array<string>, 
/**
 * 是否异步执行（command 型）
 */
async?: boolean, 
/**
 * 唤醒后重新异步执行（command 型）
 */
asyncRewake?: boolean, 
/**
 * 执行命令所用 shell（command 型）
 */
shell?: string, 
/**
 * http 目标 URL（http 型）
 */
url?: string, 
/**
 * http 请求头（http 型）
 */
headers?: { [key in string]?: string }, 
/**
 * 允许透传的环境变量名（http 型）
 */
allowedEnvVars?: Array<string>, 
/**
 * mcp 服务器名（mcp_tool 型）
 */
server?: string, 
/**
 * mcp 工具名（mcp_tool 型）
 */
tool?: string, 
/**
 * mcp_tool 入参 JSON（mcp_tool 型）
 */
input?: Record<string, unknown>, 
/**
 * prompt 内容（prompt/agent 型）
 */
prompt?: string, 
/**
 * 目标模型名（prompt/agent 型）
 */
model?: string, 
/**
 * 阻断时是否继续（prompt/agent 型）
 */
continueOnBlock?: boolean, 
/**
 * 条件表达式（仅工具事件求值）
 */
if?: string, 
/**
 * 超时秒数（通用）
 */
timeout?: number, 
/**
 * 执行状态消息（通用）
 */
statusMessage?: string, };

/**
 * hooks 配置层级（BE-18：serde 枚举 DTO——snake_case ↔ 前端 `HooksLayer` 字面量值集
 * `"user" | "project" | "local"`，硬约束 #4 双边对应）
 *
 * CP-024：ts-rs 导出命名对齐前端消费名 `HooksLayer`（Rust 名 Layer 为内部实现名）。
 */
export type HooksLayer = "user" | "project" | "local";

/**
 * matcher 组：matcher 匹配串（省略 = 全匹配，C13-5）+ handler 数组
 *
 * 形态校验（BE-18）+ 语义校验（S17 SEC-05）消费。
 * CP-024：ts-rs 导出命名对齐前端消费名 `MatcherGroupJson`。
 */
export type MatcherGroupJson = { 
/**
 * matcher 匹配串（省略 = 全匹配）
 */
matcher?: string, 
/**
 * handler 数组（必填键——形态校验拒绝缺失）
 */
hooks: Array<HookHandlerJson>, };
