// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 发送到前端的文件系统事件载荷
 *
 * CP-024:ts-rs 生成 `src/types/notify.ts`。
 */
export type FsEventPayload = { 
/**
 * 受影响的路径列表
 */
paths: Array<string>, 
/**
 * 事件类型：Create | Modify | Remove | Rescan | Other
 */
kind: string, 
/**
 * 子类型：File | Folder | Content | Name(From/To/Both) | Metadata | Any
 */
detail: string, };
