// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AmountInfo = { value: string, currency: string, };

export type PlanBalanceInfo = { sourceId: string, planId: string, frozen: boolean, amount: AmountInfo | null, windows: WindowsInfo | null, 
/**
 * 最近成功查询 unix 秒；0 = 尚无成功值（前端渲染 --）
 */
updatedAt: number, };

export type WindowInfo = { usedPercent: number, resetsAt: string | null, };

export type WindowsInfo = { fiveHour: WindowInfo, sevenDay: WindowInfo, };
