// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 模式矩阵 DTO(serde + ts-rs 双边,字段缺省走 Default)
 */
export type ConptyInputModes = { inheritCursor: boolean, resizeQuirk: boolean, win32InputMode: boolean, passthroughMode: boolean, };

/**
 * ConPTY 后端状态(CP-010:一次性查询,启动 toast 数据源)
 *
 * CP-024:ts-rs 一并导出至 pty.ts(清单外追加——手写 pty.ts 含本类型,
 * 生成物物理覆盖后需保留消费面)。
 */
export type ConptyStatus = { 
/**
 * 是否尝试捆绑(仅 Win10 build < 21376)
 */
attempted: boolean, 
/**
 * 实际是否走捆绑 conhost
 */
bundled: boolean, 
/**
 * 回退原因(attempted && !bundled 时有值,与 warn 日志同源)
 */
fallbackReason: string | null, };

/**
 * PTY 输出事件 — 通过 Channel 推送到前端
 *
 * CP-024：ts-rs 生成 `src/types/pty.ts`（tag/content 判别联合与手写面等价）。
 */
export type PtyEvent = { "type": "output", "data": { bytes: Array<number>, } } | { "type": "exit", "data": { code: number | null, } };

/**
 * spawn 参数
 *
 * CP-024：ts-rs 生成 `src/types/pty.ts`。
 */
export type SpawnRequest = { 
/**
 * 前端生成的 panel ID
 */
panelId: string, 
/**
 * 终端列数（BE-14: 反序列化后校验 ≤ i16::MAX）
 */
cols: number, 
/**
 * 终端行数（BE-14: 反序列化后校验 ≤ i16::MAX）
 */
rows: number, 
/**
 * 工作目录（可选，默认用户主目录；SEC-02: 经 validate_path_within_root 校验）
 */
cwd?: string, 
/**
 * shell 程序路径（可选，自动检测 pwsh→powershell→cmd；SEC-02: 经 validate_shell_allowlist 校验）
 */
shell?: string, };
